### ISSUE TITLE
blue/recommended dot incorrect

### ISSUE THREAD

**Issue by tdhock** [Anirban166/data.table.threads#13]
![image](https://github.com/user-attachments/assets/5dc1658c-3493-4a2b-a5e9-577306dbd3ba)
in the first panel the blue dot should be on 2 or 3 (not 1), because we can see in the plot that the black curve is greater than the blue for 2 or 3
it should be defined as the best black/empirical speedup which is greater than the recommended/blue line (default slope 0.5)

**Comment by tdhock** [comment]
@Anirban166

**Comment by Anirban166** [comment]
> in the first panel the blue dot should be on 2 or 3 (not 1), because we can see in the plot that the black curve is greater than the blue for 2 or 3 it should be defined as the best black/empirical speedup which is greater than the recommended/blue line (default slope 0.5)

You're right. I'm investigating it, and it seems like either a bug got introduced in the computation of `closestPoints` or the logic for determining the highest-value intersection of both types is incorrect. But then, it previously seemed to work (not fully accurate or to the T, but close enough) if I recall, so I'm assuming I messed up somewhere in the last few changes.

**Comment by Anirban166** [comment]
Completed in #19
