### ISSUE TITLE
please delete geom_rect

### ISSUE THREAD

**Issue by tdhock** [Anirban166/data.table.threads#15]
as I see it, the geom_rect is drawn from y=0 to y=ideal/red dot, right?
in that case it does not add any information, beyond what we can already see in the red dot, so please delete (redundantly displayed info is potentially confusing)

![image](https://github.com/user-attachments/assets/5dc1658c-3493-4a2b-a5e9-577306dbd3ba)

**Comment by tdhock** [comment]
@Anirban166

**Comment by Anirban166** [comment]
> as I see it, the geom_rect is drawn from y=0 to y=ideal/red dot, right?

It actually comes from this geometry:
https://github.com/Anirban166/data.table.threads/blob/69d3571495b65f31949d0f12f9f8a329be860894/R/plot.data_table_threads_benchmark.R#L57

> in that case it does not add any information, beyond what we can already see in the red dot, so please delete (redundantly displayed info is potentially confusing)

I agree, removing it in a minute
