### ISSUE TITLE
revise setThreadCount example in README 

### ISSUE THREAD

**Issue by tdhock** [Anirban166/data.table.threads#18]
from the README
![image](https://github.com/user-attachments/assets/58753d34-d271-4104-b24a-406155d8a60f)
which shows the threads set to 10,
it looks like that is using the ideal thread count? is that what the 0 means?
please change to 0.5 or leave undefined because the default is 0.5, right? we should not encourage users to use the red dot for the numer of threads (it is highly inefficient)
please use named arguments for clarity
```r
setOptimalThreadCount(benchmarks, functionName="forder", efficientcyFactor=0.5, verbose = TRUE)
```

**Comment by Anirban166** [comment]
Thanks!

**Comment by Anirban166** [comment]
> ... which shows the threads set to 10, it looks like that is using the ideal thread count? is that what the 0 means? 

10 is the fastest performing result that I got for `forder()`, which is the *optimal thread count* case (lowest runtime in the benchmarks, using however many threads required to achieve it)

Efficiency factor of 0 means it's not efficient in terms of speedup

**Comment by Anirban166** [comment]
> ... which shows the threads set to 10, it looks like that is using the ideal thread count? is that what the 0 means? 

10 is the fastest performing result that I got for `forder()`, which is the *optimal thread count* case (lowest runtime in the benchmarks, using however many threads required to achieve it)

Efficiency factor of 0 means it's not efficient in terms of speedup (or the user doesn't care about thread performance as they scale in numbers) but will assign the thread count to the value that accounts for the lowest runtime.

**Comment by Anirban166** [comment]
> ... which shows the threads set to 10, it looks like that is using the ideal thread count? is that what the 0 means? 

10 is the fastest performing result that I got for `forder()`, which is the *optimal thread count* case (lowest runtime in the benchmarks, using however many threads required to achieve it)

Efficiency factor of 0 means it's not efficient in terms of speedup (or the user doesn't care about thread performance as they scale in numbers) and will assign the thread count to the value that accounts for the lowest runtime.

**Comment by Anirban166** [comment]
> please change to 0.5 or leave undefined because the default is 0.5, right?

Yup the default is 0.5:
https://github.com/Anirban166/data.table.threads/blob/69d3571495b65f31949d0f12f9f8a329be860894/R/setThreadCount.r#L32

> we should not encourage users to use the red dot for the numer of threads (it is highly inefficient)

I agree
