### ISSUE TITLE
repeated logic in plot method / how to specify recommended efficiency?

### ISSUE THREAD

**Issue by tdhock** [Anirban166/data.table.threads#23]
In the plot method I see `systemThreadCount / 2` repeated
```r
    speedup = c(rep(seq(1, systemThreadCount), length(functions)), rep(seq(1, systemThreadCount / 2, length.out = systemThreadCount), length(functions))),
    type = rep(c("Ideal", "Recommended"), each = systemThreadCount * length(functions))
  )

  maxSpeedup <- x[, .(threadCount = threadCount[which.max(speedup)], speedup = max(speedup), type = "Ideal"), by = expr]

  recommendedSpeedupData <- data.table(
    threadCount = seq(1, systemThreadCount, length.out = systemThreadCount),
    speedup = seq(1, systemThreadCount / 2, length.out = systemThreadCount),
```
is this how the recommended efficiency is specified?

@Anirban166 can you please modify so that the user can specify the efficiency to use for the recommended display? (between 0 and 1)

**Comment by Anirban166** [comment]
> is this how the recommended efficiency is specified?

Yes since we discussed it to be a line of 0.5 slope on the plot (and it starts from x = 1, y = 1 since thread count values start from 1 instead of 0; starting from 0 would give a perfect 45 degree line but then the starting point being below looks weird)

**Comment by Anirban166** [comment]
> @Anirban166 can you please modify so that the user can specify the efficiency to use for the recommended display? (between 0 and 1)

Sure! I'm assuming you are thinking similar to how the `efficiencyFactor` argument in `setThreadCount()` works?
(I'll send a PR to fix the repetition and make this modification after merging #24)

**Comment by Anirban166** [comment]
> @Anirban166 can you please modify so that the user can specify the efficiency to use for the recommended display? (between 0 and 1)

Sure! I'm assuming you are thinking similar to how the `efficiencyFactor` argument in [`setThreadCount`](https://github.com/Anirban166/data.table.threads/blob/main/R/setThreadCount.r) works?
(I'll send a PR to make this modification after merging #24)

**Comment by Anirban166** [comment]
Done!

Here are some examples:

```r
benchmarkData <- findOptimalThreadCount(1e6, 10, recommendedEfficiency = 0.6)
plot(benchmarkData)
```
<img width="868" alt="image" src="https://github.com/user-attachments/assets/7404cb27-b10b-45f7-9fbe-14fbfbf00896">

```r
benchmarkData <- findOptimalThreadCount(1e7, 10, recommendedEfficiency = 0.4)
plot(benchmarkData)
```
<img width="868" alt="image" src="https://github.com/user-attachments/assets/cea3b36c-4b6d-4d23-8f49-998da05c331e">

```r
benchmarkData <- findOptimalThreadCount(1e7, 10) # default recommendedEfficiency of 0.5
plot(benchmarkData)
```
<img width="860" alt="image" src="https://github.com/user-attachments/assets/87e7cdb1-1c51-4c04-b3be-fb76c876aef7">

**Comment by Anirban166** [comment]
Thanks for the great suggestions! 

Right now I'm also wondering if we should allow the user to specify their own benchmarks to be run (for the current row-wise operations, `forder` is the only one that usually gets recommended a higher thread count value when the specified recommended efficiency is high, or at least in my machine) for even better flexibility (we would have to expose `runBenchmarks` then), but I'm happy to have at least the plot parameters be tweakable instead of rigid like this.

**Comment by tdhock** [comment]
can the efficiency parameter be moved to another function please?
you could compute the benchmarks once and then try several efficiency values with the same benchmark timings.

**Comment by tdhock** [comment]
> Right now I'm also wondering if we should allow the user to specify their own benchmarks to be run (for the current row-wise operations, forder is the only one that usually gets recommended a higher thread count value when the specified recommended efficiency is high, or at least in my machine) for even better flexibility (we would have to expose runBenchmarks then), but I'm happy to have at least the plot parameters be tweakable instead of rigid like this.

good idea but please create another issue to discuss.

**Comment by Anirban166** [comment]
> can the efficiency parameter be moved to another function please? you could compute the benchmarks once and then try several efficiency values with the same benchmark timings.

Sure! I was trying to implement this and I realize that I'm a bit confused by what you mean here - Do you mean that I should make it such that the code by default goes through multiple efficiency values? or did you mean that it would be something the user would supply, like say a range of efficiency values? (and either way, how do we determine the 'best' or most suitable one since only one particular value can be used in the plots for each function, noh?)

**Comment by tdhock** [comment]
```r
timing_data <- function1(data sizes) 
timing_data_with_efficiency_lines_in_a_list <- function2(timing_data, efficiency=0.2)
plot(timing_data_with_efficiency_lines_in_a_list)
```

**Comment by tdhock** [comment]
no please do not implement code that handles a range of efficiency values

**Comment by Anirban166** [comment]
> can the efficiency parameter be moved to another function please?
you could compute the benchmarks once and then try several efficiency values with the same benchmark timings.

I introduced changes for this in #27 (just finished fixing all the issues I had/saw, please review!) 

> ```r
> timing_data <- function1(data sizes) 
> timing_data_with_efficiency_lines_in_a_list <- function2(timing_data, efficiency=0.2)
> plot(timing_data_with_efficiency_lines_in_a_list)
> ```

Now you can do that, here's an example:
```r
(timings <- findOptimalThreadCount(1e6, 10, verbose = FALSE))
timings_with_recommended_efficiency <- addRecommendedEfficiency(timings, recommendedEfficiency = 0.4)
plot(timings_with_recommended_efficiency)
```
O/P:
```
data.table function  Thread count Fastest median runtime (ms)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
forder               10           9619.891500            
GForce_sum           1            1860.190500            
subsetting           10           4433.473500            
frollmean            1            2227.407000            
fcoalesce            3            755.507000             
between              9            2159.921000            
fifelse              8            1771.323000            
nafill               3            633.183500             
CJ                   1            403.132500   
```
<img width="847" alt="image" src="https://github.com/user-attachments/assets/aedb244b-b643-433f-835e-f75a309d7cf0">

If the user only wants ideal and measured plot data (speedup lines and thread count points) to be shown, they can avoid using `addRecommendedEfficiency` (or in my example above, just use `plot(timings)`), which I suppose is one of the main things you wanted to see out of this change?

Otherwise one simple drawback with this is that we have to make an extra function call to get the same plot as we did before (also, I didn't see mention of the recommended thread count in your example, but if you still wanted to keep that, it can only be computed when a line with slope based on recommended efficiency exists so we need both of them together)

**Comment by Anirban166** [comment]
> If the user only wants ideal and measured plot data (speedup lines and thread count points) to be shown, they can avoid using `addRecommendedEfficiency`

Here's an example:
```r
(timings <- findOptimalThreadCount(1e6, 1e2, verbose = FALSE))
plot(timings)
```
O/P:
```
data.table function  Thread count Fastest median runtime (ms)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
forder               8            9613.844000            
GForce_sum           6            1858.017500            
subsetting           8            22357.976500           
frollmean            2            2250.838500            
fcoalesce            2            758.992000             
between              4            12145.922000           
fifelse              8            1820.051500            
nafill               9            533.861000             
CJ                   5            445.096000             
```
<img width="825" alt="image" src="https://github.com/user-attachments/assets/109a4de1-5e17-4f2f-b6f6-722b385afc02">

**Comment by tdhock** [comment]
that looks better, thanks!
I wonder if the Y axis could start at 1 instead of 2.5 by default?

**Comment by Anirban166** [comment]
Anytime!

> I wonder if the Y axis could start at 1 instead of 2.5 by default?

Definitely, I only specified breaks manually for the x-axis previously (1 to max thread count in user's system) but didn't for the y-axis so I just added that in #27 

Here's an example:
```r
(timings <- findOptimalThreadCount(1e5, 10, verbose = FALSE))
timings_r <- addRecommendedEfficiency(timings, recommendedEfficiency = 0.4)
plot(timings_r)
```
```
data.table function  Thread count Fastest median runtime (ms)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
forder               8            1208.946500            
GForce_sum           2            345.117500             
subsetting           3            760.960000             
frollmean            2            242.597000             
fcoalesce            2            101.393000             
between              1            482.242000             
fifelse              3            237.369500             
nafill               2            76.957000              
CJ                   1            147.374500 
```
<img width="837" alt="image" src="https://github.com/user-attachments/assets/a42a25c6-b8f8-462e-9830-80e48bb73da3">

**Comment by Anirban166** [comment]
Actually, the uneven breaks (1.0 to 2.5 vs 2.5 to 5.0) at the start don't look good (for what I had or showed you above), but going with something as simple as `1:systemThreadCount` (like we have for the x-axis) might not look good either: (I'm thinking less breaks for the y-axis)

<img width="851" alt="image" src="https://github.com/user-attachments/assets/db3853d1-818a-4260-9bbd-bb5303c445b4">

So I'm currently computing the breaks, and to me half (compared to the number for x-axis) looks good but do you think so too? and more so, do the values look reasonable: (like 3.25, 5.5, 7.75 --> are those too much?)

<img width="871" alt="image" src="https://github.com/user-attachments/assets/97a93721-fd3c-4541-8411-57fdebe0ff14">

**Comment by tdhock** [comment]
that is better to see the 1 thanks
anyway the user can specify their own breaks if they want to override the default
